require("config.options")
require("config.keymaps")
require("config.packer")
require("config.colorscheme")

require("plugins.lsp")
require("plugins.cmp")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.autopairs")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.nvim-tree")
require("plugins.lualine")
